#!/bin/bash
cd /home/vagrant/.emacs.d
echo "(global-linum-mode t)
(show-paren-mode 1)
(setq c-default-style "bsd"
      c-basic-offset 8
      tab-width 8
      indent-tabs-mode t)
(cua-mode t)" >>init.el